# Governança Ativa (Testes Autoatizados de Qualidade)
# Conceito Aplicado: Shift Left Testing - Testes (Accuracy, Completeness, Uniqueness) 
# Serão parte inerente da esteira

version: 2

models:
  - name: dim_times
    desciption: "Tabela Dimensional SCD Type 1 com o cadastro de Times"
    columns:
      - name: team_sk
        desciption: "Chave Substituta primária"
        tests:
          - unique
          - not null

  - name: dim_torneios
    desciption: "Tabela Dimensional com histórico de Temporadas (SCD Type 2)"
    columns:
      - name: tournament_sk
        testes:
          - unique
          - not null

  - name: fct_partidas
    description: "Fato Principal contendo resultados de partidas"
    columns:
      - name: match_sk
        testes:
          - unique
          - not null
      - name: home_team_sk
        tests:
          - not null
          - relationsip: # Teste de Integridade Referencial (Accuracy)
            to: ref('dim_times')
            field: team_sk

      - name: match_season_year
        tests:
          - not null
          - accepted_values: # Teste de Validade (Validaty)
            values: [2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024]