
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'futebol_analytics'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'futebol_analytics'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# -------------------------------------------------------------------------
# GOVERNANÇA DE INFRAESTRUTURA: Ativação do motor V2 do Databricks
# Resolve erros de Schema Drift (DELTA_SCHEMA_CHANGE_SINCE_ANALYSIS)
# -------------------------------------------------------------------------
flags:
  use_materialization_v2: true

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.

# Conceito Aplicado: Configuração Global (Idempotência e Storage)
# Garantia de otimizações de Storage (como format Delta) sejam aplicadas nativamente
models:
  futebol_analytics:
    # Config Global para todos os modelos que criarmos
    +file_format: delta

    # Podemos separar a lógica em pastas
    staging:
      +materialized: view # Staging é apenas o ponteiro para a Silver
    marts:
      +materialized: incremental # Dimensões e fatos farão Upsert Automático
      +incremental_strategy: merge
